# Generated by Django 4.0.4 on 2022-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadheInd_Admin', '0002_pagetitle_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='productImage',
            field=models.FileField(null=True, upload_to='ProductImage'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productTitle',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='detail',
            field=models.CharField(max_length=5000),
        ),
    ]
