# Generated by Django 4.0.4 on 2022-05-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RadheInd_Admin', '0003_productdetails_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageTitleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pageTitleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='RadheInd_Admin.pagetitle')),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='titleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='RadheInd_Admin.pagetitleoption'),
        ),
    ]
