# Generated by Django 4.0.4 on 2022-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadheInd_Admin', '0004_pagetitleoption_alter_productdetails_titleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productImage',
            field=models.FileField(blank=True, null=True, upload_to='ProductImage'),
        ),
    ]
