# Generated by Django 4.0.4 on 2022-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadheInd_Admin', '0006_remove_productdetails_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetitleoption',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImage'),
        ),
    ]
