# Generated by Django 4.0 on 2022-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadheInd_Admin', '0009_certificates_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happyClients', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('hoursOfSupport', models.IntegerField(default=0)),
                ('hardWork', models.IntegerField(default=0)),
            ],
        ),
    ]
